import { Geist, Geist_Mono } from "next/font/google";
import "./(resources)/(css)/bootstrap.css";
import "./(resources)/(css)/globals.css";
import Navbar from "../(components)/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "WFN",
    template: "WFN | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
